project_id = "ptditjhezxiwdeqqoezc"

[functions.chat]
verify_jwt = true

[functions.suggest-folder]
verify_jwt = true

[functions.extract-image]
verify_jwt = true

[functions.studybody]
verify_jwt = true

[functions.delete-account]
verify_jwt = true
