-- Personalization import: the student pastes a "who I am" summary generated by
-- an AI they already study with. We store it here and feed it into G&D's chat
-- prompts so answers are tailored from day one.
alter table public.user_profiles
add column if not exists personalization_background text;
